### ISSUE TITLE
feat: Frontend Docker Container Setup

### ISSUE THREAD

**Issue by ivangrynenko** [truecms/sentinel#48]
# Frontend Docker Container Setup

**Type**: Feature  
**Priority**: Critical  
**Epic**: Frontend Foundation  
**Estimated Effort**: 2 days

## Description

Set up Docker container for the frontend application that integrates with the existing Docker Compose setup and can communicate with the backend API.

## Technical Requirements

- Multi-stage Dockerfile for development and production
- Integration with existing docker-compose.yml
- Proper networking to connect with backend API
- Hot module replacement for development
- Nginx for production serving
- Environment variable configuration

## Acceptance Criteria

- [ ] Dockerfile created with multi-stage build
- [ ] Development container with hot reload working
- [ ] Production container with Nginx serving static files
- [ ] Frontend can communicate with backend API within Docker network
- [ ] Environment variables properly passed to container
- [ ] Docker Compose updated to include frontend service
- [ ] Health check endpoint configured
- [ ] Documentation updated with Docker commands

### Dockerfile.frontend
```dockerfile
# Development stage
FROM node:18-alpine AS development
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
EXPOSE 3000
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]

# Build stage
FROM node:18-alpine AS build
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
RUN npm run build

# Production stage
FROM nginx:alpine AS production
COPY --from=build /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
```

### Docker Compose Addition
```yaml
frontend:
  build:
    context: ./frontend
    dockerfile: Dockerfile.frontend
    target: development
  ports:
    - "3000:3000"
  volumes:
    - ./frontend:/app
    - /app/node_modules
  environment:
    - VITE_API_URL=http://api:8000/api/v1
    - VITE_WS_URL=ws://api:8000/ws
  depends_on:
    - api
  networks:
    - app-network
```

### nginx.conf for Production
```nginx
server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /api {
        proxy_pass http://api:8000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }

    location /ws {
        proxy_pass http://api:8000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_set_header Host $host;
    }
}
```

## Dependencies

- Docker and Docker Compose installed
- Backend API service running

## Notes

- Ensure the frontend container can resolve the `api` hostname within the Docker network
- Use build arguments for different environments
- Consider adding a `.dockerignore` file to exclude unnecessary files
- Test both development and production builds
